# Generated by Django 4.0 on 2022-01-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Важно'), (2, 'Средней срочности'), (3, 'Совсем не срочно')], default=1, verbose_name='Срочность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
