# Generated by Django 4.0 on 2022-01-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task_date_alter_task_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
    ]
