# Generated by Django 4.0 on 2022-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_time',
            field=models.DateTimeField(blank=True, default=1, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
