# Generated by Django 4.0 on 2022-02-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_task_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_time',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, default=1, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(blank=True, default=2, verbose_name='Время'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('срочно и важно', 'Срочно и важно'), ('срочно, но не важно', 'Срочно, но не важно'), ('несрочно, но важно', 'Несрочно, но важно'), ('несрочно и не важно', 'Несрочно и не важно')], max_length=50, verbose_name='Срочность'),
        ),
    ]
